package com.qingshixun.project.eshop.module.promo.dao;

import com.qingshixun.project.eshop.module.promo.dao.dataobject.PromoDO;
import com.qingshixun.project.eshop.web.MyBatisRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@MyBatisRepository
public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Aug 25 14:52:10 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Aug 25 14:52:10 CST 2019
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Aug 25 14:52:10 CST 2019
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Aug 25 14:52:10 CST 2019
     */
    PromoDO selectByPrimaryKey(Long id);

    PromoDO selectByItemId(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Aug 25 14:52:10 CST 2019
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Aug 25 14:52:10 CST 2019
     */
    int updateByPrimaryKey(PromoDO record);

    void decreasePromoItemNum(Long itemId);


    List<PromoDO> listPromo();

}